---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ganamovil-ganamovil-bff-staging
  namespace: argocd
spec:
  project: az-devops-gitops
  source:
    repoURL: https://BancoGanadero@dev.azure.com/BancoGanadero/BGA-Internal/_git/gitops
    path: infra/ganamovil/ganamovil-bff
    targetRevision: main
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ganamovil-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
