---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "project.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
  {{- range .Values.tls.certs }}
    - hosts:
        {{- range .hosts }}
      - {{ .host }}
        {{ end }}
      secretName: {{ .secretName }}
  {{ end }}
  {{ end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
        {{- range .paths }}
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          path: {{ .path }}
          pathType: {{ .pathType }}
        {{ end }}
      {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
  {{ end }}
{{ end }}