---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project.fullname" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "project.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ default "http" .Values.service.portName | quote }}
      port: {{ default 80 .Values.service.port }}
      targetPort: {{ default 80 .Values.service.targetPort }}
      protocol: {{ default "TCP" .Values.service.protocol | upper }}
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default 30000 .Values.service.nodePort }}
      {{- end }}
